epvserver:
  image: estimatedplacentalvolume/epv-server:latest
  ports:
    - 8080:8080
    - 8081:8081
    - 8000:8000
  links:
    - mysql:mysql
  environment:
    - DEBUG=true

mysql:
  image: mysql:5.5
  environment:
    - MYSQL_ROOT_PASSWORD=my_sql_root_password
    - MYSQL_DATABASE=epv
    - MYSQL_USER=epv
    - MYSQL_PASSWORD=my_sql_epv_password
