epvserver:
  image: estimatedplacentalvolume/epv-server:latest
  ports:
    - 8080:8080
    - 8081:8081
  links:
    - mysql:mysql
  environment:
    - DEBUG=true
    - EPV_SERVER_USER=epvapp
    - EPV_SERVER_SHA256_PASSWORD=a4aae22c3cf93d97c13715c097e57cc987f5c3cebb71c26887ac6f088f0d9a17

mysql:
  image: mysql:5.5
  environment:
    - MYSQL_ROOT_PASSWORD=my_sql_root_password
    - MYSQL_DATABASE=epv
    - MYSQL_USER=epv
    - MYSQL_PASSWORD=my_sql_epv_password

epvnginx:
  image: estimatedplacentalvolume/epv-nginx:latest
  links:
    - epvserver:epv-server
  ports:
    - 80:80
    - 443:443
